load("province_bmr_sum.Rda")
load("district_bmr_sum.Rda")

###########################################
# CREATING CONSISTENT PROVINCE BOUNDARIES #
###########################################

bmr_sum_fn <- function(i){
  i %>% 
    group_by(tinh) %>% 
    summarise(tot_bmr_prov = sum(tot_bmr_prov),
              tot_bmr_lb_prov = sum(tot_bmr_lb_prov),
              killed_tot_prov = sum(killed_tot_prov),
              dist_nearest_base_prov = min(dist_nearest_base_prov),
              dist_nearest_hochi_prov = min(dist_nearest_hochi_prov)) %>% 
    select(tinh, everything()) %>% 
    mutate(mean_tot_bmr_prov = mean(tot_bmr_prov, na.rm = T),
           sd_tot_bmr_prov = sd(tot_bmr_prov, na.rm = T),
           tot_bmr_prov_std = (tot_bmr_prov - mean_tot_bmr_prov)/sd_tot_bmr_prov) %>% 
    select(-c(mean_tot_bmr_prov, sd_tot_bmr_prov))
}

bombs_province89 <- province_bmr_sum %>%
  ungroup() %>% 
  mutate(tinh = recode(name_1,
                       'Hậu Giang' = 43,
                       'Hà Nội' = 1,
                       'Hải Phòng' = 3,
                       'Hải Dương' = 21,
                       'Hưng Yên' = 21,
                       'Nam Định' = 23,
                       'Hà Nam' = 23,
                       'Ninh Bình' = 23,
                       'Thái Bình' = 22,
                       'Hà Giang' = 11,
                       'Cao Bằng' = 10,
                       'Lào Cai' = 14,
                       'Bắc Kạn' = 15,
                       'Lạng Sơn' = 12,
                       'Tuyên Quang' = 11,
                       'Yên Bái' = 14,
                       'Thái Nguyên' = 15,
                       'Phú Thọ' = 17,
                       'Vĩnh Phúc' = 17,
                       'Bắc Giang' = 18,
                       'Bắc Ninh' = 18,
                       'Quảng Ninh' = 19,
                       'Lai Châu' = 13,
                       'Hoà Bình' = 20,
                       'Thanh Hóa' = 24,
                       'Nghệ An'= 25,
                       'Hà Tĩnh' = 25,
                       'Quảng Bình' = 26,
                       'Quảng Trị' = 49,
                       'Thừa Thiên Huế' = 50,
                       'Đà Nẵng' = 27,
                       'Quảng Nam' = 27,
                       'Quảng Ngãi' = 47,
                       'Bình Định' = 28,
                       'Phú Yên' = 48,
                       'Khánh Hòa' = 29,
                       'Kon Tum' = 31,
                       'Gia Lai' = 31,
                       'Đắk Lắk' = 32,
                       'Đắk Nông' = 32,
                       'Hồ Chí Minh' = 2,
                       'Lâm Đồng' = 33,
                       'Ninh Thuận' = 30,
                       'Bình Phước' = 34,
                       'Tây Ninh' = 35,
                       'Bình Dương' = 34,
                       'Đồng Nai' = 36,
                       'Bình Thuận' = 30,
                       'Bà Rịa - Vũng Tàu' = 46,
                       'Long An' = 37,
                       'Đồng Tháp' = 38,
                       'An Giang' = 39,
                       'Tiền Giang' = 40,
                       'Vĩnh Long' = 42,
                       'Bến Tre' = 41,
                       'Kiên Giang' = 44,
                       'Cần Thơ' = 43,
                       'Trà Vinh' = 42,
                       'Sóc Trăng' = 43,
                       'Bạc Liêu' = 45,
                       'Cà Mau' = 45,
                       'Sơn La' = 16,
                       .default = NA_real_)) %>% 
  bmr_sum_fn() %>% 
  rename(geo1_vn1989 = tinh)

bombs_province99 <- province_bmr_sum %>%
  ungroup() %>% 
  mutate(tinh = recode(name_1,
                       'Hậu Giang' = 301,
                       'Hà Nội' = 101,
                       'Hải Phòng' = 103,
                       'Hải Dương' = 107,
                       'Hưng Yên' = 109,
                       'Nam Định' = 113,
                       'Hà Nam' = 111,
                       'Ninh Bình' = 117,
                       'Thái Bình' = 115,
                       'Hà Giang' = 201,
                       'Cao Bằng' = 203,
                       'Lào Cai' = 205,
                       'Bắc Kạn' = 207,
                       'Lạng Sơn' = 209,
                       'Tuyên Quang' = 211,
                       'Yên Bái' = 213,
                       'Thái Nguyên' = 215,
                       'Phú Thọ' = 217,
                       'Vĩnh Phúc' = 219,
                       'Bắc Giang' = 221,
                       'Bắc Ninh' = 223,
                       'Quảng Ninh' = 225,
                       'Lai Châu' = 301,
                       'Hoà Bình' = 305,
                       'Thanh Hóa' = 401,
                       'Nghệ An'= 403,
                       'Hà Tĩnh' = 405,
                       'Quảng Bình' = 407,
                       'Quảng Trị' = 409,
                       'Thừa Thiên Huế' = 411,
                       'Đà Nẵng' = 501,
                       'Quảng Nam' = 507,
                       'Quảng Ngãi' = 503,
                       'Bình Định' = 505,
                       'Phú Yên' = 509,
                       'Khánh Hòa' = 511,
                       'Kon Tum' = 601,
                       'Gia Lai' = 603,
                       'Đắk Lắk' = 605,
                       'Đắk Nông' = 605,
                       'Hồ Chí Minh' = 701,
                       'Lâm Đồng' = 703,
                       'Ninh Thuận' = 705,
                       'Bình Phước' = 707,
                       'Tây Ninh' = 709,
                       'Bình Dương' = 711,
                       'Đồng Nai' = 713,
                       'Bình Thuận' = 715,
                       'Bà Rịa - Vũng Tàu' = 717,
                       'Long An' = 801,
                       'Đồng Tháp' = 803,
                       'An Giang' = 805,
                       'Tiền Giang' = 807,
                       'Vĩnh Long' = 809,
                       'Bến Tre' = 811,
                       'Kiên Giang' = 813,
                       'Cần Thơ' = 815,
                       'Trà Vinh' = 817,
                       'Sóc Trăng' = 819,
                       'Bạc Liêu' = 821,
                       'Cà Mau' = 823,
                       'Sơn La' = 303,
                       'Điện Biên' = 301,
                       .default = NA_real_)) %>% 
  bmr_sum_fn() %>% 
  rename(geo1_vn1999 = tinh)

bombs_province09 <- province_bmr_sum %>%
  mutate(tinh = recode(name_1,
                       'Đắk Nông' = 67,
                       'Hậu Giang' = 93,
                       'Hà Nội' = 1,
                       'Hải Phòng' = 31,
                       'Hải Dương' = 30,
                       'Hưng Yên' = 33,
                       'Nam Định' = 36,
                       'Hà Nam' = 35,
                       'Ninh Bình' = 37,
                       'Thái Bình' = 34,
                       'Hà Giang' = 2,
                       'Cao Bằng' = 4,
                       'Lào Cai' = 10,
                       'Bắc Kạn' = 6,
                       'Lạng Sơn' = 20,
                       'Tuyên Quang' = 8,
                       'Yên Bái' = 15,
                       'Thái Nguyên' = 19,
                       'Phú Thọ' = 25,
                       'Vĩnh Phúc' = 26,
                       'Bắc Giang' = 24,
                       'Bắc Ninh' = 27,
                       'Quảng Ninh' = 22,
                       'Lai Châu' = 12,
                       'Hoà Bình' = 17,
                       'Thanh Hóa' = 38,
                       'Nghệ An'= 40,
                       'Hà Tĩnh' = 42,
                       'Quảng Bình' = 44,
                       'Quảng Trị' = 45,
                       'Thừa Thiên Huế' = 46,
                       'Đà Nẵng' = 48,
                       'Quảng Nam' = 49,
                       'Quảng Ngãi' = 51,
                       'Bình Định' = 52,
                       'Phú Yên' = 54,
                       'Khánh Hòa' = 56,
                       'Kon Tum' = 62,
                       'Gia Lai' = 64,
                       'Đắk Lắk' = 66,
                       'Hồ Chí Minh' = 79,
                       'Lâm Đồng' = 68,
                       'Ninh Thuận' = 58,
                       'Bình Phước' = 70,
                       'Tây Ninh' = 72,
                       'Bình Dương' = 74,
                       'Đồng Nai' = 75,
                       'Bình Thuận' = 60,
                       'Bà Rịa - Vũng Tàu' = 77,
                       'Long An' = 80,
                       'Đồng Tháp' = 87,
                       'An Giang' = 89,
                       'Tiền Giang' = 82,
                       'Vĩnh Long' = 86,
                       'Bến Tre' = 83,
                       'Kiên Giang' = 91,
                       'Cần Thơ' = 92,
                       'Trà Vinh' = 84,
                       'Sóc Trăng' = 94,
                       'Bạc Liêu' = 95,
                       'Cà Mau' = 96,
                       'Sơn La' = 14,
                       'Điện Biên' = 11,
                       .default = NA_real_)) %>% 
  bmr_sum_fn() %>% 
  rename(geo1_vn2009 = tinh)

save(bombs_province89, file = "bombs_province89.Rda")
save(bombs_province99, file = "bombs_province99.Rda")
save(bombs_province09, file = "bombs_province09.Rda")

#########
# VHLSS #
#########

