#################################
# Firm level FE - FORMAL WORKERS #
##################################

dn_manu_prov_n <- (list(
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_01) | lhdn + nganh_kd,
        subset(dn01, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | lhdn + nganh_kd,
        subset(dn02, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03) | lhdn + nganh_kd,
        subset(dn03, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04)| lhdn + nganh_kd,
        subset(dn04, south == 0 & manu == 1),
        vcov = ~tinh), 
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05)| lhdn + nganh_kd,
        subset(dn05, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06)| lhdn + nganh_kd,
        subset(dn06, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07)| lhdn + nganh_kd,
        subset(dn07, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08)| lhdn + nganh_kd,
        subset(dn08, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09)| lhdn + nganh_kd,
        subset(dn09, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10)| lhdn + nganh_kd,
        subset(dn10, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11)| lhdn + nganh_kd,
        subset(dn11, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12)| lhdn + nganh_kd,
        subset(dn12, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13)| lhdn + nganh_kd,
        subset(dn13, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 + log(popdensity_14)| lhdn + nganh_kd,
        subset(dn14, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 + log(popdensity_15)| lhdn + nganh_kd,
        subset(dn15, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 + log(popdensity_16)| lhdn + nganh_kd,
        subset(dn16, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 + log(popdensity_17)| lhdn + nganh_kd,
        subset(dn17, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18 + log(popdensity_18)| lhdn + nganh_kd,
        subset(dn18, south == 0 & manu == 1),
        vcov = ~tinh)))

dn_manu_prov_s <- (list(
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_01) | lhdn + nganh_kd,
        subset(dn01, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | lhdn + nganh_kd,
        subset(dn02, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03) | lhdn + nganh_kd,
        subset(dn03, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04) | lhdn + nganh_kd,
        subset(dn04, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05) | lhdn + nganh_kd,
        subset(dn05, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06) | lhdn + nganh_kd,
        subset(dn06, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07) | lhdn + nganh_kd,
        subset(dn07, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08) | lhdn + nganh_kd,
        subset(dn08, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09) | lhdn + nganh_kd,
        subset(dn09, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10) | lhdn + nganh_kd,
        subset(dn10, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11) | lhdn + nganh_kd,
        subset(dn11, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12) | lhdn + nganh_kd,
        subset(dn12, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13) | lhdn + nganh_kd,
        subset(dn13, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 + log(popdensity_14) | lhdn + nganh_kd,
        subset(dn14, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 + log(popdensity_15) | lhdn + nganh_kd,
        subset(dn15, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 + log(popdensity_16) | lhdn + nganh_kd,
        subset(dn16, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 + log(popdensity_17) | lhdn + nganh_kd,
        subset(dn17, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18 + log(popdensity_18) | lhdn + nganh_kd,
        subset(dn18, south == 1 & manu == 1),
        vcov = ~tinh)))

dn_manu_prov_coef_n <- lapply(dn_manu_prov_n, tidy)
dn_manu_prov_coef_s <- lapply(dn_manu_prov_s, tidy)
dn_manu_prov_coef_n <- do.call(rbind, dn_manu_prov_coef_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_manu_prov_coef_s <- do.call(rbind, dn_manu_prov_coef_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_manu_prov_coef_n$year <- rep(seq(2001, 2018), each = nrow(dn_manu_prov_coef_n) / length(seq(2001, 2018)))
dn_manu_prov_coef_s$year <- rep(seq(2001, 2018), each = nrow(dn_manu_prov_coef_s) / length(seq(2001, 2018)))

dn_manu_prov_coef_n$group <- "North"
dn_manu_prov_coef_s$group <- "South"
dn_manu_prov_coef_ns <- rbind(dn_manu_prov_coef_n, dn_manu_prov_coef_s)

# By formal 

dn_manu_formal_prov_n <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | lhdn + nganh_kd,
        subset(dn02, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03) | lhdn + nganh_kd,
        subset(dn03, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04)| lhdn + nganh_kd,
        subset(dn04, south == 0 & manu == 1),
        vcov = ~tinh), 
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05)| lhdn + nganh_kd,
        subset(dn05, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06)| lhdn + nganh_kd,
        subset(dn06, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07)| lhdn + nganh_kd,
        subset(dn07, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08)| lhdn + nganh_kd,
        subset(dn08, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09)| lhdn + nganh_kd,
        subset(dn09, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10)| lhdn + nganh_kd,
        subset(dn10, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11)| lhdn + nganh_kd,
        subset(dn11, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12)| lhdn + nganh_kd,
        subset(dn12, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13)| lhdn + nganh_kd,
        subset(dn13, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 + log(popdensity_14)| lhdn + nganh_kd,
        subset(dn14, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 + log(popdensity_15)| lhdn + nganh_kd,
        subset(dn15, south == 0 & manu == 1),
        vcov = ~tinh)))

dn_manu_formal_prov_s <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | lhdn + nganh_kd,
        subset(dn02, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03) | lhdn + nganh_kd,
        subset(dn03, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04) | lhdn + nganh_kd,
        subset(dn04, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05) | lhdn + nganh_kd,
        subset(dn05, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06) | lhdn + nganh_kd,
        subset(dn06, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07) | lhdn + nganh_kd,
        subset(dn07, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08) | lhdn + nganh_kd,
        subset(dn08, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09) | lhdn + nganh_kd,
        subset(dn09, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10) | lhdn + nganh_kd,
        subset(dn10, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11) | lhdn + nganh_kd,
        subset(dn11, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12) | lhdn + nganh_kd,
        subset(dn12, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13) | lhdn + nganh_kd,
        subset(dn13, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 + log(popdensity_14) | lhdn + nganh_kd,
        subset(dn14, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 + log(popdensity_15) | lhdn + nganh_kd,
        subset(dn15, south == 1 & manu == 1),
        vcov = ~tinh)))

dn_manu_formal_prov_coef_n <- lapply(dn_manu_formal_prov_n, tidy)
dn_manu_formal_prov_coef_s <- lapply(dn_manu_formal_prov_s, tidy)
dn_manu_formal_prov_coef_n <- do.call(rbind, dn_manu_formal_prov_coef_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_manu_formal_prov_coef_s <- do.call(rbind, dn_manu_formal_prov_coef_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_manu_formal_prov_coef_n$year <- rep(seq(2002, 2015), each = nrow(dn_manu_formal_prov_coef_n) / length(seq(2002, 2015)))
dn_manu_formal_prov_coef_s$year <- rep(seq(2002, 2015), each = nrow(dn_manu_formal_prov_coef_s) / length(seq(2002, 2015)))

dn_manu_formal_prov_coef_n$group <- "North"
dn_manu_formal_prov_coef_s$group <- "South"
dn_manu_formal_prov_coef_ns <- rbind(dn_manu_formal_prov_coef_n, dn_manu_formal_prov_coef_s)

################
# By firm type #
################

# SOE 

dn_soe_n <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | nganh_kd,
        subset(dn02, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03)  | nganh_kd,
        subset(dn03, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04) | nganh_kd,
        subset(dn04, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05) | nganh_kd,
        subset(dn05, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06) | nganh_kd,
        subset(dn06, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07) | nganh_kd,
        subset(dn07, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08) | nganh_kd,
        subset(dn08, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09) | nganh_kd,
        subset(dn09, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10) | nganh_kd,
        subset(dn10, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11) | nganh_kd,
        subset(dn11, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12) | nganh_kd,
        subset(dn12, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13) | nganh_kd,
        subset(dn13, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14  + log(popdensity_14) | nganh_kd,
        subset(dn14, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15  + log(popdensity_15) | nganh_kd,
        subset(dn15, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 + log(popdensity_16) | nganh_kd,
        subset(dn16, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 + log(popdensity_17) | nganh_kd,
        subset(dn17, south == 0 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18 + log(popdensity_18) | nganh_kd,
        subset(dn18, south == 0 & soe == 1),
        vcov = ~tinh)))

dn_soe_s <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  + log(popdensity_02) | nganh_kd,
        subset(dn02, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  + log(popdensity_03) | nganh_kd,
        subset(dn03, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_04) | nganh_kd,
        subset(dn04, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_05) | nganh_kd,
        subset(dn05, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_06) | nganh_kd,
        subset(dn06, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07  + log(popdensity_07) | nganh_kd,
        subset(dn07, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08  + log(popdensity_08) | nganh_kd,
        subset(dn08, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09  + log(popdensity_09) | nganh_kd,
        subset(dn09, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10  + log(popdensity_10) | nganh_kd,
        subset(dn10, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11  + log(popdensity_11) | nganh_kd,
        subset(dn11, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12  + log(popdensity_12) | nganh_kd,
        subset(dn12, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13  + log(popdensity_13) | nganh_kd,
        subset(dn13, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14  + log(popdensity_14) | nganh_kd,
        subset(dn14, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15  + log(popdensity_15) | nganh_kd,
        subset(dn15, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 + log(popdensity_16) | nganh_kd,
        subset(dn16, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 + log(popdensity_17) | nganh_kd,
        subset(dn17, south == 1 & soe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18 + log(popdensity_18) | nganh_kd,
        subset(dn18, south == 1 & soe == 1),
        vcov = ~tinh)))

dn_soe_n <- lapply(dn_soe_n, tidy)
dn_soe_s <- lapply(dn_soe_s, tidy)
dn_soe_n <- do.call(rbind, dn_soe_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_soe_s <- do.call(rbind, dn_soe_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_soe_n$year <- rep(seq(2002, 2018), each = nrow(dn_soe_n) / length(seq(2002, 2018)))
dn_soe_s$year <- rep(seq(2002, 2018), each = nrow(dn_soe_s) / length(seq(2002, 2018)))

dn_soe_n$group <- "North"
dn_soe_s$group <- "South"
dn_soe_ns <- rbind(dn_soe_n, dn_soe_s)

# FOE

dn_foe_n <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | nganh_kd,
        subset(dn02, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03)  | nganh_kd,
        subset(dn03, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04) | nganh_kd,
        subset(dn04, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05) | nganh_kd,
        subset(dn05, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06) | nganh_kd,
        subset(dn06, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07) | nganh_kd,
        subset(dn07, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08) | nganh_kd,
        subset(dn08, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09) | nganh_kd,
        subset(dn09, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10) | nganh_kd,
        subset(dn10, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11) | nganh_kd,
        subset(dn11, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12) | nganh_kd,
        subset(dn12, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13) | nganh_kd,
        subset(dn13, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14  + log(popdensity_14) | nganh_kd,
        subset(dn14, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15  + log(popdensity_15) | nganh_kd,
        subset(dn15, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16  + log(popdensity_16) | nganh_kd,
        subset(dn16, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17  + log(popdensity_17) | nganh_kd,
        subset(dn17, south == 0 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18  + log(popdensity_18) | nganh_kd,
        subset(dn18, south == 0 & foe == 1),
        vcov = ~tinh)))

dn_foe_s <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  + log(popdensity_02) | nganh_kd,
        subset(dn02, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  + log(popdensity_03) | nganh_kd,
        subset(dn03, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_04) | nganh_kd,
        subset(dn04, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_05) | nganh_kd,
        subset(dn05, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_06) | nganh_kd,
        subset(dn06, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07  + log(popdensity_07) | nganh_kd,
        subset(dn07, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08  + log(popdensity_08) | nganh_kd,
        subset(dn08, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09  + log(popdensity_09) | nganh_kd,
        subset(dn09, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10  + log(popdensity_10) | nganh_kd,
        subset(dn10, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11  + log(popdensity_11) | nganh_kd,
        subset(dn11, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12  + log(popdensity_12) | nganh_kd,
        subset(dn12, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13  + log(popdensity_13) | nganh_kd,
        subset(dn13, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14  + log(popdensity_14) | nganh_kd,
        subset(dn14, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15  + log(popdensity_15) | nganh_kd,
        subset(dn15, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16  + log(popdensity_16) | nganh_kd,
        subset(dn16, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17  + log(popdensity_17) | nganh_kd,
        subset(dn17, south == 1 & foe == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18  + log(popdensity_18) | nganh_kd,
        subset(dn18, south == 1 & foe == 1),
        vcov = ~tinh)))

dn_foe_n <- lapply(dn_foe_n, tidy)
dn_foe_s <- lapply(dn_foe_s, tidy)
dn_foe_n <- do.call(rbind, dn_foe_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_foe_s <- do.call(rbind, dn_foe_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_foe_n$year <- rep(seq(2002, 2018), each = nrow(dn_foe_n) / length(seq(2002, 2018)))
dn_foe_s$year <- rep(seq(2002, 2018), each = nrow(dn_foe_s) / length(seq(2002, 2018)))

dn_foe_n$group <- "North"
dn_foe_s$group <- "South"
dn_foe_ns <- rbind(dn_foe_n, dn_foe_s)

# Private 

dn_private_n <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | nganh_kd,
        subset(dn02, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03)  | nganh_kd,
        subset(dn03, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04) | nganh_kd,
        subset(dn04, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05) | nganh_kd,
        subset(dn05, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06) | nganh_kd,
        subset(dn06, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07) | nganh_kd,
        subset(dn07, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08) | nganh_kd,
        subset(dn08, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09) | nganh_kd,
        subset(dn09, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10) | nganh_kd,
        subset(dn10, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11) | nganh_kd,
        subset(dn11, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12) | nganh_kd,
        subset(dn12, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13) | nganh_kd,
        subset(dn13, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14  + log(popdensity_14) | nganh_kd,
        subset(dn14, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15  + log(popdensity_15) | nganh_kd,
        subset(dn15, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16  + log(popdensity_16) | nganh_kd,
        subset(dn16, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17  + log(popdensity_17) | nganh_kd,
        subset(dn17, south == 0 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18  + log(popdensity_18) | nganh_kd,
        subset(dn18, south == 0 & private == 1),
        vcov = ~tinh)))

dn_private_s <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  + log(popdensity_02) | nganh_kd,
        subset(dn02, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  + log(popdensity_03) | nganh_kd,
        subset(dn03, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_04) | nganh_kd,
        subset(dn04, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_05) | nganh_kd,
        subset(dn05, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_06) | nganh_kd,
        subset(dn06, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07  + log(popdensity_07) | nganh_kd,
        subset(dn07, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08  + log(popdensity_08) | nganh_kd,
        subset(dn08, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09  + log(popdensity_09) | nganh_kd,
        subset(dn09, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10  + log(popdensity_10) | nganh_kd,
        subset(dn10, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11  + log(popdensity_11) | nganh_kd,
        subset(dn11, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12  + log(popdensity_12) | nganh_kd,
        subset(dn12, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13  + log(popdensity_13) | nganh_kd,
        subset(dn13, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14  + log(popdensity_14) | nganh_kd,
        subset(dn14, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15  + log(popdensity_15) | nganh_kd,
        subset(dn15, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16  + log(popdensity_16) | nganh_kd,
        subset(dn16, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17  + log(popdensity_17) | nganh_kd,
        subset(dn17, south == 1 & private == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18  + log(popdensity_18) | nganh_kd,
        subset(dn18, south == 1 & private == 1),
        vcov = ~tinh)))

dn_private_n <- lapply(dn_private_n, tidy)
dn_private_s <- lapply(dn_private_s, tidy)
dn_private_n <- do.call(rbind, dn_private_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_private_s <- do.call(rbind, dn_private_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_private_n$year <- rep(seq(2002, 2018), each = nrow(dn_private_n) / length(seq(2002, 2018)))
dn_private_s$year <- rep(seq(2002, 2018), each = nrow(dn_private_s) / length(seq(2002, 2018)))

dn_private_n$group <- "North"
dn_private_s$group <- "South"
dn_private_ns <- rbind(dn_private_n, dn_private_s)

# Private w/ State funding 

dn_priv_w_state_n <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | nganh_kd,
        subset(dn02, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03)  | nganh_kd,
        subset(dn03, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04) | nganh_kd,
        subset(dn04, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05) | nganh_kd,
        subset(dn05, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06) | nganh_kd,
        subset(dn06, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07) | nganh_kd,
        subset(dn07, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08) | nganh_kd,
        subset(dn08, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09) | nganh_kd,
        subset(dn09, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10) | nganh_kd,
        subset(dn10, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11) | nganh_kd,
        subset(dn11, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12) | nganh_kd,
        subset(dn12, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13) | nganh_kd,
        subset(dn13, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14  + log(popdensity_14) | nganh_kd,
        subset(dn14, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15  + log(popdensity_15) | nganh_kd,
        subset(dn15, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16  + log(popdensity_16) | nganh_kd,
        subset(dn16, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17  + log(popdensity_17) | nganh_kd,
        subset(dn17, south == 0 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18  + log(popdensity_18) | nganh_kd,
        subset(dn18, south == 0 & priv_w_state == 1),
        vcov = ~tinh)))

dn_priv_w_state_s <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  + log(popdensity_02) | nganh_kd,
        subset(dn02, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  + log(popdensity_03) | nganh_kd,
        subset(dn03, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_04) | nganh_kd,
        subset(dn04, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_05) | nganh_kd,
        subset(dn05, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_06) | nganh_kd,
        subset(dn06, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07  + log(popdensity_07) | nganh_kd,
        subset(dn07, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08  + log(popdensity_08) | nganh_kd,
        subset(dn08, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09  + log(popdensity_09) | nganh_kd,
        subset(dn09, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10  + log(popdensity_10) | nganh_kd,
        subset(dn10, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11  + log(popdensity_11) | nganh_kd,
        subset(dn11, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12  + log(popdensity_12) | nganh_kd,
        subset(dn12, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13  + log(popdensity_13) | nganh_kd,
        subset(dn13, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14  + log(popdensity_14) | nganh_kd,
        subset(dn14, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15  + log(popdensity_15) | nganh_kd,
        subset(dn15, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16  + log(popdensity_16) | nganh_kd,
        subset(dn16, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17  + log(popdensity_17) | nganh_kd,
        subset(dn17, south == 1 & priv_w_state == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18  + log(popdensity_18) | nganh_kd,
        subset(dn18, south == 1 & priv_w_state == 1),
        vcov = ~tinh)))

dn_priv_w_state_n <- lapply(dn_priv_w_state_n, tidy)
dn_priv_w_state_s <- lapply(dn_priv_w_state_s, tidy)
dn_priv_w_state_n <- do.call(rbind, dn_priv_w_state_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_priv_w_state_s <- do.call(rbind, dn_priv_w_state_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_priv_w_state_n$year <- rep(seq(2002, 2018), each = nrow(dn_priv_w_state_n) / length(seq(2002, 2018)))
dn_priv_w_state_s$year <- rep(seq(2002, 2018), each = nrow(dn_priv_w_state_s) / length(seq(2002, 2018)))

dn_priv_w_state_n$group <- "North"
dn_priv_w_state_s$group <- "South"
dn_priv_w_state_ns <- rbind(dn_priv_w_state_n, dn_priv_w_state_s)
