#################################
# Firm level FE - FORMAL WORKERS #
##################################

dn_manu_prov_n <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_01) | nganh_kd + lhdn,
        subset(dn01, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | nganh_kd + lhdn,
        subset(dn02, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03) | nganh_kd + lhdn,
        subset(dn03, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04)| nganh_kd + lhdn,
        subset(dn04, south == 0 & manu == 1),
        vcov = ~tinh), 
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05)| nganh_kd + lhdn,
        subset(dn05, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06)| nganh_kd + lhdn,
        subset(dn06, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07)| nganh_kd + lhdn,
        subset(dn07, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08)| nganh_kd + lhdn,
        subset(dn08, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09)| nganh_kd + lhdn,
        subset(dn09, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10)| nganh_kd + lhdn,
        subset(dn10, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11)| nganh_kd + lhdn,
        subset(dn11, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12)| nganh_kd + lhdn,
        subset(dn12, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13)| nganh_kd + lhdn,
        subset(dn13, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 + log(popdensity_14)| nganh_kd + lhdn,
        subset(dn14, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 + log(popdensity_15)| nganh_kd + lhdn,
        subset(dn15, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 + log(popdensity_16)| nganh_kd + lhdn,
        subset(dn16, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 + log(popdensity_17)| nganh_kd + lhdn,
        subset(dn17, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18 + log(popdensity_18)| nganh_kd + lhdn,
        subset(dn18, south == 0 & manu == 1),
        vcov = ~tinh)))

dn_manu_prov_s <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_01) | nganh_kd + lhdn,
        subset(dn01, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | nganh_kd + lhdn,
        subset(dn02, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03) | nganh_kd + lhdn,
        subset(dn03, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04) | nganh_kd + lhdn,
        subset(dn04, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05) | nganh_kd + lhdn,
        subset(dn05, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06) | nganh_kd + lhdn,
        subset(dn06, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07) | nganh_kd + lhdn,
        subset(dn07, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08) | nganh_kd + lhdn,
        subset(dn08, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09) | nganh_kd + lhdn,
        subset(dn09, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10) | nganh_kd + lhdn,
        subset(dn10, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11) | nganh_kd + lhdn,
        subset(dn11, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12) | nganh_kd + lhdn,
        subset(dn12, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13) | nganh_kd + lhdn,
        subset(dn13, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 + log(popdensity_14) | nganh_kd + lhdn,
        subset(dn14, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 + log(popdensity_15) | nganh_kd + lhdn,
        subset(dn15, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 + log(popdensity_16) | nganh_kd + lhdn,
        subset(dn16, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 + log(popdensity_17) | nganh_kd + lhdn,
        subset(dn17, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18 + log(popdensity_18) | nganh_kd + lhdn,
        subset(dn18, south == 1 & manu == 1),
        vcov = ~tinh)))

dn_manu_prov_coef_n <- lapply(dn_manu_prov_n, tidy)
dn_manu_prov_coef_s <- lapply(dn_manu_prov_s, tidy)
dn_manu_prov_coef_n <- do.call(rbind, dn_manu_prov_coef_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_manu_prov_coef_s <- do.call(rbind, dn_manu_prov_coef_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_manu_prov_coef_n$year <- rep(seq(2001, 2018), each = nrow(dn_manu_prov_coef_n) / length(seq(2001, 2018)))
dn_manu_prov_coef_s$year <- rep(seq(2001, 2018), each = nrow(dn_manu_prov_coef_s) / length(seq(2001, 2018)))

dn_manu_prov_coef_n$group <- "North"
dn_manu_prov_coef_s$group <- "South"
dn_manu_prov_coef_ns <- rbind(dn_manu_prov_coef_n, dn_manu_prov_coef_s)

# By formal 

dn_manu_formal_prov_n <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_01) | nganh_kd + lhdn,
        subset(dn01, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | nganh_kd + lhdn,
        subset(dn02, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03) | nganh_kd + lhdn,
        subset(dn03, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04)| nganh_kd + lhdn,
        subset(dn04, south == 0 & manu == 1),
        vcov = ~tinh), 
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05)| nganh_kd + lhdn,
        subset(dn05, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06)| nganh_kd + lhdn,
        subset(dn06, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07)| nganh_kd + lhdn,
        subset(dn07, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08)| nganh_kd + lhdn,
        subset(dn08, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09)| nganh_kd + lhdn,
        subset(dn09, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10)| nganh_kd + lhdn,
        subset(dn10, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11)| nganh_kd + lhdn,
        subset(dn11, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12)| nganh_kd + lhdn,
        subset(dn12, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13)| nganh_kd + lhdn,
        subset(dn13, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 + log(popdensity_14)| nganh_kd + lhdn,
        subset(dn14, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 + log(popdensity_15)| nganh_kd + lhdn,
        subset(dn15, south == 0 & manu == 1),
        vcov = ~tinh)))

dn_manu_formal_prov_s <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_01) | nganh_kd + lhdn,
        subset(dn01, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | nganh_kd + lhdn,
        subset(dn02, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03) | nganh_kd + lhdn,
        subset(dn03, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04) | nganh_kd + lhdn,
        subset(dn04, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05) | nganh_kd + lhdn,
        subset(dn05, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06) | nganh_kd + lhdn,
        subset(dn06, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07) | nganh_kd + lhdn,
        subset(dn07, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08) | nganh_kd + lhdn,
        subset(dn08, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09) | nganh_kd + lhdn,
        subset(dn09, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10) | nganh_kd + lhdn,
        subset(dn10, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11) | nganh_kd + lhdn,
        subset(dn11, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12) | nganh_kd + lhdn,
        subset(dn12, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13) | nganh_kd + lhdn,
        subset(dn13, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 + log(popdensity_14) | nganh_kd + lhdn,
        subset(dn14, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 + log(popdensity_15) | nganh_kd + lhdn,
        subset(dn15, south == 1 & manu == 1),
        vcov = ~tinh)))

dn_manu_formal_prov_coef_n <- lapply(dn_manu_formal_prov_n, tidy)
dn_manu_formal_prov_coef_s <- lapply(dn_manu_formal_prov_s, tidy)
dn_manu_formal_prov_coef_n <- do.call(rbind, dn_manu_formal_prov_coef_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_manu_formal_prov_coef_s <- do.call(rbind, dn_manu_formal_prov_coef_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_manu_formal_prov_coef_n$year <- rep(seq(2001, 2015), each = nrow(dn_manu_formal_prov_coef_n) / length(seq(2001, 2015)))
dn_manu_formal_prov_coef_s$year <- rep(seq(2001, 2015), each = nrow(dn_manu_formal_prov_coef_s) / length(seq(2001, 2015)))

dn_manu_formal_prov_coef_n$group <- "North"
dn_manu_formal_prov_coef_s$group <- "South"
dn_manu_formal_prov_coef_ns <- rbind(dn_manu_formal_prov_coef_n, dn_manu_formal_prov_coef_s)
