## By south 
dn_ols_manu_prov_n <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_01) | lhdn + nganh_kd,
        subset(dn01, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_02) | lhdn + nganh_kd,
        subset(dn02, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio + log(popdensity_03)  | lhdn + nganh_kd,
        subset(dn03, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_04) | lhdn + nganh_kd,
        subset(dn04, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_05) | lhdn + nganh_kd,
        subset(dn05, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 + log(popdensity_06) | lhdn + nganh_kd,
        subset(dn06, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 + log(popdensity_07) | lhdn + nganh_kd,
        subset(dn07, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 + log(popdensity_08) | lhdn + nganh_kd,
        subset(dn08, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 + log(popdensity_09) | lhdn + nganh_kd,
        subset(dn09, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 + log(popdensity_10) | lhdn + nganh_kd,
        subset(dn10, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 + log(popdensity_11) | lhdn + nganh_kd,
        subset(dn11, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 + log(popdensity_12) | lhdn + nganh_kd,
        subset(dn12, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 + log(popdensity_13) | lhdn + nganh_kd,
        subset(dn13, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14  + log(popdensity_14) | lhdn + nganh_kd,
        subset(dn14, south == 0 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15  + log(popdensity_15) | lhdn + nganh_kd,
        subset(dn15, south == 0 & manu == 1),
        vcov = ~tinh)))

dn_ols_manu_prov_s <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  + log(popdensity_01) | lhdn + nganh_kd,
        subset(dn01, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  + log(popdensity_02) | lhdn + nganh_kd,
        subset(dn02, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  + log(popdensity_03) | lhdn + nganh_kd,
        subset(dn03, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_04) | lhdn + nganh_kd,
        subset(dn04, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_05) | lhdn + nganh_kd,
        subset(dn05, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05  + log(popdensity_06) | lhdn + nganh_kd,
        subset(dn06, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07  + log(popdensity_07) | lhdn + nganh_kd,
        subset(dn07, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08  + log(popdensity_08) | lhdn + nganh_kd,
        subset(dn08, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09  + log(popdensity_09) | lhdn + nganh_kd,
        subset(dn09, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10  + log(popdensity_10) | lhdn + nganh_kd,
        subset(dn10, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11  + log(popdensity_11) | lhdn + nganh_kd,
        subset(dn11, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12  + log(popdensity_12) | lhdn + nganh_kd,
        subset(dn12, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13  + log(popdensity_13) | lhdn + nganh_kd,
        subset(dn13, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14  + log(popdensity_14) | lhdn + nganh_kd,
        subset(dn14, south == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15  + log(popdensity_15) | lhdn + nganh_kd,
        subset(dn15, south == 1 & manu == 1),
        vcov = ~tinh)))

dn_ols_manu_prov_coef_n <- lapply(dn_ols_manu_prov_n, tidy)
dn_ols_manu_prov_coef_s <- lapply(dn_ols_manu_prov_s, tidy)
dn_ols_manu_prov_coef_n <- do.call(rbind, dn_ols_manu_prov_coef_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_ols_manu_prov_coef_s <- do.call(rbind, dn_ols_manu_prov_coef_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_ols_manu_prov_coef_n$year <- rep(seq(2001, 2018), each = nrow(dn_ols_manu_prov_coef_n) / length(seq(2001, 2018)))
dn_ols_manu_prov_coef_s$year <- rep(seq(2001, 2018), each = nrow(dn_ols_manu_prov_coef_s) / length(seq(2001, 2018)))

dn_ols_manu_prov_coef_n$group <- "North"
dn_ols_manu_prov_coef_s$group <- "South"
dn_ols_manu_prov_coef_ns <- rbind(dn_ols_manu_prov_coef_n, dn_ols_manu_prov_coef_s)

#################################
# Firm level FE - FORMAL WORKERS #
##################################

# By south 

dn_manu_formal_prov_n <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn01, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn02, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn03, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn04, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn05, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn06, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | lhdn + nganh_kd,
        subset(dn07, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn + nganh_kd,
        subset(dn08, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | lhdn + nganh_kd,
        subset(dn09, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | lhdn + nganh_kd,
        subset(dn10, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | lhdn + nganh_kd,
        subset(dn11, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | lhdn + nganh_kd,
        subset(dn12, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | lhdn + nganh_kd,
        subset(dn13, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | lhdn + nganh_kd,
        subset(dn14, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | lhdn + nganh_kd,
        subset(dn15, south == 0 & manu == 1 & manu == 1),
        vcov = ~tinh)))

dn_manu_formal_prov_s <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn01, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn02, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn03, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn04, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn05, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn06, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | lhdn + nganh_kd,
        subset(dn07, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn + nganh_kd,
        subset(dn08, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | lhdn + nganh_kd,
        subset(dn09, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | lhdn + nganh_kd,
        subset(dn10, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | lhdn + nganh_kd,
        subset(dn11, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | lhdn + nganh_kd,
        subset(dn12, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | lhdn + nganh_kd,
        subset(dn13, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | lhdn + nganh_kd,
        subset(dn14, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | lhdn + nganh_kd,
        subset(dn15, south == 1 & manu == 1 & manu == 1),
        vcov = ~tinh)))

dn_manu_formal_prov_coef_n <- lapply(dn_manu_formal_prov_n, tidy)
dn_manu_formal_prov_coef_s <- lapply(dn_manu_formal_prov_s, tidy)
dn_manu_formal_prov_coef_n <- do.call(rbind, dn_manu_formal_prov_coef_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_manu_formal_prov_coef_s <- do.call(rbind, dn_manu_formal_prov_coef_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_manu_formal_prov_coef_n$year <- rep(seq(2001, 2015), each = nrow(dn_manu_formal_prov_coef_n) / length(seq(2001, 2015)))
dn_manu_formal_prov_coef_s$year <- rep(seq(2001, 2015), each = nrow(dn_manu_formal_prov_coef_s) / length(seq(2001, 2015)))

dn_manu_formal_prov_coef_n$group <- "North"
dn_manu_formal_prov_coef_s$group <- "South"
dn_manu_formal_prov_coef_ns <- rbind(dn_manu_formal_prov_coef_n, dn_manu_formal_prov_coef_s)
