################################
# Firm level OLS - ALL WORKERS #
################################

dn_ols_prov <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        dn01,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        dn02,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        dn03,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        dn04,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        dn05,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        dn06,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | lhdn,
        dn07,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn,
        dn08,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | lhdn,
        dn09,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | lhdn,
        dn10,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | lhdn,
        dn11,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | lhdn,
        dn12,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | lhdn,
        dn13,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | lhdn,
        dn14,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | lhdn,
        dn15,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 | lhdn,
        dn16,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 | lhdn,
        dn17,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18 | lhdn,
        dn18,
        vcov = ~tinh)))

dn_ols_coef_prov<- lapply(dn_ols_prov, tidy)
dn_ols_coef_prov <- do.call(rbind, dn_ols_coef_prov) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_ols_coef_prov$year <- rep(seq(2001, 2018), each = nrow(dn_ols_coef_prov) / length(seq(2001, 2018)))

## By south 
dn_ols_prov_n <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        subset(dn01, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        subset(dn02, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio  | lhdn,
        subset(dn03, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn04, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn05, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn06, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | lhdn,
        subset(dn07, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn,
        subset(dn08, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | lhdn,
        subset(dn09, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | lhdn,
        subset(dn10, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | lhdn,
        subset(dn11, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | lhdn,
        subset(dn12, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | lhdn,
        subset(dn13, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | lhdn,
        subset(dn14, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | lhdn,
        subset(dn15, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 | lhdn,
        subset(dn16, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 | lhdn,
        subset(dn17, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn,
        subset(dn18, south == 0),
        vcov = ~tinh)))

dn_ols_prov_s <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        subset(dn01, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        subset(dn02, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        subset(dn03, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn04, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn05, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn06, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | lhdn,
        subset(dn07, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn,
        subset(dn08, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | lhdn,
        subset(dn09, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | lhdn,
        subset(dn10, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | lhdn,
        subset(dn11, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | lhdn,
        subset(dn12, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | lhdn,
        subset(dn13, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | lhdn,
        subset(dn14, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | lhdn,
        subset(dn15, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 | lhdn,
        subset(dn16, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 | lhdn,
        subset(dn17, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18 | lhdn,
        subset(dn18, south == 1),
        vcov = ~tinh)))

dn_ols_prov_coef_n <- lapply(dn_ols_prov_n, tidy)
dn_ols_prov_coef_s <- lapply(dn_ols_prov_s, tidy)
dn_ols_prov_coef_n <- do.call(rbind, dn_ols_prov_coef_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_ols_prov_coef_s <- do.call(rbind, dn_ols_prov_coef_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_ols_prov_coef_n$year <- rep(seq(2001, 2018), each = nrow(dn_ols_prov_coef_n) / length(seq(2001, 2018)))
dn_ols_prov_coef_s$year <- rep(seq(2001, 2018), each = nrow(dn_ols_prov_coef_s) / length(seq(2001, 2018)))

dn_ols_prov_coef_n$group <- "North"
dn_ols_prov_coef_s$group <- "South"
dn_ols_prov_coef_ns <- rbind(dn_ols_prov_coef_n, dn_ols_prov_coef_s)

###############################
# Firm level FE - ALL WORKERS #
###############################

dn_indfe_prov <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        dn01,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        dn02,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        dn03,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        dn04,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        dn05,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        dn06,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | nganh_kd + lhdn,
        dn07,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | nganh_kd + lhdn,
        dn08,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | nganh_kd + lhdn,
        dn09,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | nganh_kd + lhdn,
        dn10,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11| nganh_kd + lhdn,
        dn11,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | nganh_kd + lhdn,
        dn12,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | nganh_kd + lhdn,
        dn13,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | nganh_kd + lhdn,
        dn14,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | nganh_kd + lhdn,
        dn15,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 | nganh_kd + lhdn,
        dn16,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 | nganh_kd + lhdn,
        dn17,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18 | nganh_kd + lhdn,
        dn18,
        vcov = ~tinh)))

dn_indfe_prov_coef <- lapply(dn_indfe_prov, tidy) 
dn_indfe_prov_coef <- do.call(rbind, dn_indfe_prov_coef) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_indfe_prov_coef$year <- rep(seq(2001, 2018), each = nrow(dn_indfe_prov_coef) / length(seq(2001, 2018)))

## By north/south 
dn_indfe_prov_n <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        subset(dn01, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        subset(dn02, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        subset(dn03, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        subset(dn04, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        subset(dn05, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        subset(dn06, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | nganh_kd + lhdn,
        subset(dn07, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | nganh_kd + lhdn,
        subset(dn08, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | nganh_kd + lhdn,
        subset(dn09, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | nganh_kd + lhdn,
        subset(dn10, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | nganh_kd + lhdn,
        subset(dn11, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | nganh_kd + lhdn,
        subset(dn12, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | nganh_kd + lhdn,
        subset(dn13, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | nganh_kd + lhdn,
        subset(dn14, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | nganh_kd + lhdn,
        subset(dn15, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 | nganh_kd + lhdn,
        subset(dn16, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 | nganh_kd + lhdn,
        subset(dn17, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18 | nganh_kd + lhdn,
        subset(dn18, south == 0),
        vcov = ~tinh)))

dn_indfe_prov_s <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        subset(dn01, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        subset(dn02, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        subset(dn03, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        subset(dn04, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        subset(dn05, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        subset(dn06, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | nganh_kd + lhdn,
        subset(dn07, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | nganh_kd + lhdn,
        subset(dn08, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | nganh_kd + lhdn,
        subset(dn09, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | nganh_kd + lhdn,
        subset(dn10, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | nganh_kd + lhdn,
        subset(dn11, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | nganh_kd + lhdn,
        subset(dn12, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | nganh_kd + lhdn,
        subset(dn13, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | nganh_kd + lhdn,
        subset(dn14, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | nganh_kd + lhdn,
        subset(dn15, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio16 | nganh_kd + lhdn,
        subset(dn16, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio17 | nganh_kd + lhdn,
        subset(dn17, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov_ppn) + sexratio18 | nganh_kd + lhdn,
        subset(dn18, south == 1),
        vcov = ~tinh)))

dn_indfe_prov_coef_n <- lapply(dn_indfe_prov_n, tidy)
dn_indfe_prov_coef_s <- lapply(dn_indfe_prov_s, tidy)
dn_indfe_prov_coef_n <- do.call(rbind, dn_indfe_prov_coef_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_indfe_prov_coef_s <- do.call(rbind, dn_indfe_prov_coef_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_indfe_prov_coef_n$year <- rep(seq(2001, 2018), each = nrow(dn_indfe_prov_coef_n) / length(seq(2001, 2018)))
dn_indfe_prov_coef_s$year <- rep(seq(2001, 2018), each = nrow(dn_indfe_prov_coef_s) / length(seq(2001, 2018)))

dn_indfe_prov_coef_n$group <- "North"
dn_indfe_prov_coef_s$group <- "South"
dn_indfe_prov_coef_ns <- rbind(dn_indfe_prov_coef_n, dn_indfe_prov_coef_s)

###################################
# Firm level OLS - FORMAL WORKERS #
###################################

dn_formal_ols_prov <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        dn01,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        dn02,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        dn03,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        dn04,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        dn05,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        dn06,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | lhdn,
        dn07,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn,
        dn08,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | lhdn,
        dn09,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | lhdn,
        dn10,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | lhdn,
        dn11,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | lhdn,
        dn12,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | lhdn,
        dn13,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | lhdn,
        dn14,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | lhdn,
        dn15,
        vcov = ~tinh)))

dn_formal_ols_coef_prov<- lapply(dn_formal_ols_prov, tidy)
dn_formal_ols_coef_prov <- do.call(rbind, dn_formal_ols_coef_prov) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_formal_ols_coef_prov$year <- rep(seq(2001, 2015), each = nrow(dn_formal_ols_coef_prov) / length(seq(2001, 2015)))

# By south 

dn_formal_ols_prov_n <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        subset(dn01, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        subset(dn02, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        subset(dn03, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn04, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn05, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn06, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | lhdn,
        subset(dn07, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn,
        subset(dn08, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | lhdn,
        subset(dn09, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | lhdn,
        subset(dn10, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | lhdn,
        subset(dn11, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | lhdn,
        subset(dn12, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | lhdn,
        subset(dn13, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | lhdn,
        subset(dn14, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | lhdn,
        subset(dn15, south == 0),
        vcov = ~tinh)))

dn_formal_ols_prov_s <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        subset(dn01, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        subset(dn02, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn,
        subset(dn03, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn04, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn05, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn,
        subset(dn06, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | lhdn,
        subset(dn07, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn,
        subset(dn08, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | lhdn,
        subset(dn09, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | lhdn,
        subset(dn10, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | lhdn,
        subset(dn11, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | lhdn,
        subset(dn12, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | lhdn,
        subset(dn13, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | lhdn,
        subset(dn14, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | lhdn,
        subset(dn15, south == 1),
        vcov = ~tinh)))

dn_formal_ols_prov_coef_n <- lapply(dn_formal_ols_prov_n, tidy)
dn_formal_ols_prov_coef_s <- lapply(dn_formal_ols_prov_s, tidy)
dn_formal_ols_prov_coef_n <- do.call(rbind, dn_formal_ols_prov_coef_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_formal_ols_prov_coef_s <- do.call(rbind, dn_formal_ols_prov_coef_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_formal_ols_prov_coef_n$year <- rep(seq(2001, 2015), each = nrow(dn_formal_ols_prov_coef_n) / length(seq(2001, 2015)))
dn_formal_ols_prov_coef_s$year <- rep(seq(2001, 2015), each = nrow(dn_formal_ols_prov_coef_s) / length(seq(2001, 2015)))

dn_formal_ols_prov_coef_n$group <- "North"
dn_formal_ols_prov_coef_s$group <- "South"
dn_formal_ols_prov_coef_ns <- rbind(dn_formal_ols_prov_coef_n, dn_formal_ols_prov_coef_s)

#################################
# Firm level FE - FORMAL WORKERS #
##################################

dn_formal_fe_prov <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        dn01,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        dn02,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        dn03,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        dn04,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        dn05,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        dn06,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | lhdn + nganh_kd,
        dn07,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn + nganh_kd,
        dn08,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | lhdn + nganh_kd,
        dn09,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | lhdn + nganh_kd,
        dn10,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | lhdn + nganh_kd,
        dn11,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | lhdn + nganh_kd,
        dn12,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | lhdn + nganh_kd,
        dn13,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | lhdn + nganh_kd,
        dn14,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | lhdn + nganh_kd,
        dn15,
        vcov = ~tinh)))

dn_formal_fe_prov_coef <- lapply(dn_formal_fe_prov, tidy)
dn_formal_fe_prov_coef <- do.call(rbind, dn_formal_fe_prov_coef) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_formal_fe_prov_coef$year <- rep(seq(2001, 2015), each = nrow(dn_formal_fe_prov_coef) / length(seq(2001, 2015)))

# By south 

dn_formal_fe_prov_n <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn01, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn02, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn03, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn04, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn05, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn06, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | lhdn + nganh_kd,
        subset(dn07, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn + nganh_kd,
        subset(dn08, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | lhdn + nganh_kd,
        subset(dn09, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | lhdn + nganh_kd,
        subset(dn10, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | lhdn + nganh_kd,
        subset(dn11, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | lhdn + nganh_kd,
        subset(dn12, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | lhdn + nganh_kd,
        subset(dn13, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | lhdn + nganh_kd,
        subset(dn14, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | lhdn + nganh_kd,
        subset(dn15, south == 0),
        vcov = ~tinh)))

dn_formal_fe_prov_s <- (list(
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn01, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn02, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        subset(dn03, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn04, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn05, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        subset(dn06, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio07 | lhdn + nganh_kd,
        subset(dn07, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio08 | lhdn + nganh_kd,
        subset(dn08, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio09 | lhdn + nganh_kd,
        subset(dn09, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio10 | lhdn + nganh_kd,
        subset(dn10, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio11 | lhdn + nganh_kd,
        subset(dn11, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio12 | lhdn + nganh_kd,
        subset(dn12, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio13 | lhdn + nganh_kd,
        subset(dn13, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio14 | lhdn + nganh_kd,
        subset(dn14, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov_ppn) + sexratio15 | lhdn + nganh_kd,
        subset(dn15, south == 1),
        vcov = ~tinh)))

dn_formal_fe_coef_prov_n <- lapply(dn_formal_fe_prov_n, tidy)
dn_formal_fe_coef_prov_s <- lapply(dn_formal_fe_prov_s, tidy)
dn_formal_fe_coef_prov_n <- do.call(rbind, dn_formal_fe_coef_prov_n) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_formal_fe_coef_prov_s <- do.call(rbind, dn_formal_fe_coef_prov_s) %>% filter(term == "log(tot_bmr_prov_ppn)")
dn_formal_fe_coef_prov_n$year <- rep(seq(2001, 2015), each = nrow(dn_formal_fe_coef_prov_n) / length(seq(2001, 2015)))
dn_formal_fe_coef_prov_s$year <- rep(seq(2001, 2015), each = nrow(dn_formal_fe_coef_prov_s) / length(seq(2001, 2015)))

dn_formal_fe_coef_prov_n$group <- "North"
dn_formal_fe_coef_prov_s$group <- "South"
dn_formal_fe_coef_prov_ns <- rbind(dn_formal_fe_coef_prov_n, dn_formal_fe_coef_prov_s)

##################################
# Casualties - OLS - ALL WORKERS #
##################################

dn_ols_prov_cas <- (list(
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | lhdn,
        dn01,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | lhdn,
        dn02,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | lhdn,
        dn03,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | lhdn,
        dn04,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | lhdn,
        dn05,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | lhdn,
        dn06,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio07 | lhdn,
        dn07,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio08 | lhdn,
        dn08,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio09 | lhdn,
        dn09,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio10 | lhdn,
        dn10,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio11 | lhdn,
        dn11,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio12 | lhdn,
        dn12,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio13 | lhdn,
        dn13,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio14 | lhdn,
        dn14,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio15 | lhdn,
        dn15,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio16 | lhdn,
        dn16,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio17 | lhdn,
        dn17,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio18 | lhdn,
        dn18,
        vcov = ~tinh)))

dn_ols_prov_cas_coef <- lapply(dn_ols_prov_cas, tidy)
dn_ols_prov_cas_coef <- do.call(rbind, dn_ols_prov_cas_coef) %>% filter(term == "log(killed_tot_prov_ppn)")
dn_ols_prov_cas_coef$year <- rep(seq(2001, 2018), each = nrow(dn_ols_prov_cas_coef) / length(seq(2001, 2018)))

#####################################
# Casualties - OLS - FORMAL WORKERS #
#####################################

dn_formal_ols_prov_cas <- (list(
  feols(workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | lhdn,
        dn01,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | lhdn,
        dn02,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | lhdn,
        dn03,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | lhdn,
        dn04,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | lhdn,
        dn05,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | lhdn,
        dn06,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio07 | lhdn,
        dn07,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio08 | lhdn,
        dn08,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio09 | lhdn,
        dn09,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio10 | lhdn,
        dn10,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio11 | lhdn,
        dn11,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio12 | lhdn,
        dn12,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio13 | lhdn,
        dn13,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio14 | lhdn,
        dn14,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio15 | lhdn,
        dn15,
        vcov = ~tinh)))

dn_formal_ols_prov_coef_cas<- lapply(dn_formal_ols_prov_cas, tidy)
dn_formal_ols_prov_coef_cas <- do.call(rbind, dn_formal_ols_prov_coef_cas) %>% filter(term == "log(killed_tot_prov_ppn)")
dn_formal_ols_prov_coef_cas$year <- rep(seq(2001, 2015), each = nrow(dn_formal_ols_prov_coef_cas) / length(seq(2001, 2015)))

#################################
# Casualties - FE - ALL WORKERS #
#################################

dn_indfe_prov_cas <- (list(
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        dn01,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        dn02,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | nganh_kd + lhdn,
        dn03,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        dn04,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        dn05,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | nganh_kd + lhdn,
        dn06,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio07 | nganh_kd + lhdn,
        dn07,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio08 | nganh_kd + lhdn,
        dn08,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio09 | nganh_kd + lhdn,
        dn09,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio10 | nganh_kd + lhdn,
        dn10,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio11| nganh_kd + lhdn,
        dn11,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio12 | nganh_kd + lhdn,
        dn12,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio13 | nganh_kd + lhdn,
        dn13,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio14 | nganh_kd + lhdn,
        dn14,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio15 | nganh_kd + lhdn,
        dn15,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio16 | nganh_kd + lhdn,
        dn16,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio17 | nganh_kd + lhdn,
        dn17,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(killed_tot_prov_ppn) + sexratio18 | nganh_kd + lhdn,
        dn18,
        vcov = ~tinh)))

dn_indfe_prov_coef_cas <- lapply(dn_indfe_prov_cas, tidy) 
dn_indfe_prov_coef_cas <- do.call(rbind, dn_indfe_prov_coef_cas) %>% filter(term == "log(killed_tot_prov_ppn)")
dn_indfe_prov_coef_cas$year <- rep(seq(2001, 2018), each = nrow(dn_indfe_prov_coef_cas) / length(seq(2001, 2018)))

####################################
# Casualties - FE - FORMAL WORKERS #
####################################

dn_formal_fe_prov_cas <- (list(
  feols(workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        dn01,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        dn02,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sex_ratio | lhdn + nganh_kd,
        dn03,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        dn04,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        dn05,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio05 | lhdn + nganh_kd,
        dn06,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio07 | lhdn + nganh_kd,
        dn07,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio08 | lhdn + nganh_kd,
        dn08,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio09 | lhdn + nganh_kd,
        dn09,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio10 | lhdn + nganh_kd,
        dn10,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio11 | lhdn + nganh_kd,
        dn11,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio12 | lhdn + nganh_kd,
        dn12,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio13 | lhdn + nganh_kd,
        dn13,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio14 | lhdn + nganh_kd,
        dn14,
        vcov = ~tinh),
  feols(workerratio ~ log(killed_tot_prov_ppn) + sexratio15 | lhdn + nganh_kd,
        dn15,
        vcov = ~tinh)))

dn_workerratio_coef_prov_cas <- lapply(dn_formal_fe_prov_cas, tidy)
dn_workerratio_coef_prov_cas <- do.call(rbind, dn_workerratio_coef_prov_cas) %>% filter(term == "log(killed_tot_prov_ppn)")
dn_workerratio_coef_prov_cas$year <- rep(seq(2001, 2015), each = nrow(dn_workerratio_coef_prov_cas) / length(seq(2001, 2015)))

##################
# FEMALE DORECTOR#
##################

# By year of establishment 


femaledir_yob_fe_prov_s <-  tidy(feols(female_dir ~ i(dir_yob, log(tot_bmr_prov_ppn)) + sexratio16 | nganh_kd + lhdn + dir_yob + dir_ethnicity,
                                       subset(dn16, south == 1 & dir_yob > 1951 & dir_yob < 1991),
                                       vcov = ~tinh + dir_yob)) %>% filter(grepl("log\\(tot_bmr_prov_ppn\\)", term))
femaledir_yob_fe_prov_n <-  tidy(feols(female_dir ~ i(dir_yob, log(tot_bmr_prov_ppn)) + sexratio16 | nganh_kd + lhdn + dir_yob + dir_ethnicity,
                                       subset(dn16, south == 0 & dir_yob > 1951 & dir_yob < 1991),
                                       vcov = ~tinh + dir_yob)) %>% filter(grepl("log\\(tot_bmr_prov_ppn\\)", term))

femaledir_yob_fe_prov_n$year <- rep(seq(1952, 1990), each = nrow(femaledir_yob_fe_prov_n) / length(seq(1952, 1990)))
femaledir_yob_fe_prov_s$year <- rep(seq(1952, 1990), each = nrow(femaledir_yob_fe_prov_s) / length(seq(1952, 1990)))

femaledir_yob_fe_prov_n$group <- "North"
femaledir_yob_fe_prov_s$group <- "South"
femaledir_yob_fe_prov_s_ns <- rbind(femaledir_yob_fe_prov_n, femaledir_yob_fe_prov_s)
