###############################
# Firm level FE - ALL WORKERS #
###############################

dn_indfe_prov_rc <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov) + sex_ratio | nganh_kd + lhdn,
        dn01,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sex_ratio | nganh_kd + lhdn,
        dn02,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sex_ratio | nganh_kd + lhdn,
        dn03,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio05 | nganh_kd + lhdn,
        dn04,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio05 | nganh_kd + lhdn,
        dn05,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio05 | nganh_kd + lhdn,
        dn06,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio07 | nganh_kd + lhdn,
        dn07,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio08 | nganh_kd + lhdn,
        dn08,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio09 | nganh_kd + lhdn,
        dn09,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio10 | nganh_kd + lhdn,
        dn10,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio11| nganh_kd + lhdn,
        dn11,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio12 | nganh_kd + lhdn,
        dn12,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio13 | nganh_kd + lhdn,
        dn13,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio14 | nganh_kd + lhdn,
        dn14,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio15 | nganh_kd + lhdn,
        dn15,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio16 | nganh_kd + lhdn,
        dn16,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio17 | nganh_kd + lhdn,
        dn17,
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio18 | nganh_kd + lhdn,
        dn18,
        vcov = ~tinh)))

dn_indfe_prov_rc_coef <- lapply(dn_indfe_prov_rc, tidy) 
dn_indfe_prov_rc_coef <- do.call(rbind, dn_indfe_prov_rc_coef) %>% filter(term == "log(tot_bmr_prov)")
dn_indfe_prov_rc_coef$year <- rep(seq(2001, 2018), each = nrow(dn_indfe_prov_rc_coef) / length(seq(2001, 2018)))

## By north/south 
dn_indfe_prov_rc_n <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov) + sex_ratio | nganh_kd + lhdn,
        subset(dn01, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sex_ratio | nganh_kd + lhdn,
        subset(dn02, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sex_ratio | nganh_kd + lhdn,
        subset(dn03, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio05 | nganh_kd + lhdn,
        subset(dn04, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio05 | nganh_kd + lhdn,
        subset(dn05, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio05 | nganh_kd + lhdn,
        subset(dn06, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio07 | nganh_kd + lhdn,
        subset(dn07, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio08 | nganh_kd + lhdn,
        subset(dn08, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio09 | nganh_kd + lhdn,
        subset(dn09, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio10 | nganh_kd + lhdn,
        subset(dn10, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio11 | nganh_kd + lhdn,
        subset(dn11, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio12 | nganh_kd + lhdn,
        subset(dn12, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio13 | nganh_kd + lhdn,
        subset(dn13, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio14 | nganh_kd + lhdn,
        subset(dn14, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio15 | nganh_kd + lhdn,
        subset(dn15, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio16 | nganh_kd + lhdn,
        subset(dn16, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio17 | nganh_kd + lhdn,
        subset(dn17, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio18 | nganh_kd + lhdn,
        subset(dn18, south == 0),
        vcov = ~tinh)))

dn_indfe_prov_rc_s <- (list(
  feols(tot_workerratio ~ log(tot_bmr_prov) + sex_ratio | nganh_kd + lhdn,
        subset(dn01, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sex_ratio | nganh_kd + lhdn,
        subset(dn02, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sex_ratio | nganh_kd + lhdn,
        subset(dn03, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio05 | nganh_kd + lhdn,
        subset(dn04, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio05 | nganh_kd + lhdn,
        subset(dn05, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio05 | nganh_kd + lhdn,
        subset(dn06, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio07 | nganh_kd + lhdn,
        subset(dn07, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio08 | nganh_kd + lhdn,
        subset(dn08, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio09 | nganh_kd + lhdn,
        subset(dn09, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio10 | nganh_kd + lhdn,
        subset(dn10, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio11 | nganh_kd + lhdn,
        subset(dn11, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio12 | nganh_kd + lhdn,
        subset(dn12, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio13 | nganh_kd + lhdn,
        subset(dn13, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio14 | nganh_kd + lhdn,
        subset(dn14, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio15 | nganh_kd + lhdn,
        subset(dn15, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio16 | nganh_kd + lhdn,
        subset(dn16, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio17 | nganh_kd + lhdn,
        subset(dn17, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov) + sexratio18 | nganh_kd + lhdn,
        subset(dn18, south == 1),
        vcov = ~tinh)))

dn_indfe_prov_rc_coef_n <- lapply(dn_indfe_prov_rc_n, tidy)
dn_indfe_prov_rc_coef_s <- lapply(dn_indfe_prov_rc_s, tidy)
dn_indfe_prov_rc_coef_n <- do.call(rbind, dn_indfe_prov_rc_coef_n) %>% filter(term == "log(tot_bmr_prov)")
dn_indfe_prov_rc_coef_s <- do.call(rbind, dn_indfe_prov_rc_coef_s) %>% filter(term == "log(tot_bmr_prov)")
dn_indfe_prov_rc_coef_n$year <- rep(seq(2001, 2018), each = nrow(dn_indfe_prov_rc_coef_n) / length(seq(2001, 2018)))
dn_indfe_prov_rc_coef_s$year <- rep(seq(2001, 2018), each = nrow(dn_indfe_prov_rc_coef_s) / length(seq(2001, 2018)))

dn_indfe_prov_rc_coef_n$group <- "North"
dn_indfe_prov_rc_coef_s$group <- "South"
dn_indfe_prov_rc_coef_ns <- rbind(dn_indfe_prov_rc_coef_n, dn_indfe_prov_rc_coef_s)

###################################
# Firm level OLS - FORMAL WORKERS #
###################################

dn_formal_ols_prov_rc <- (list(
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn,
        dn01,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn,
        dn02,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn,
        dn03,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn,
        dn04,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn,
        dn05,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn,
        dn06,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio07 | lhdn,
        dn07,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio08 | lhdn,
        dn08,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio09 | lhdn,
        dn09,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio10 | lhdn,
        dn10,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio11 | lhdn,
        dn11,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio12 | lhdn,
        dn12,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio13 | lhdn,
        dn13,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio14 | lhdn,
        dn14,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio15 | lhdn,
        dn15,
        vcov = ~tinh)))

dn_formal_ols_coef_prov_rc <- lapply(dn_formal_ols_prov_rc, tidy)
dn_formal_ols_coef_prov_rc <- do.call(rbind, dn_formal_ols_coef_prov_rc) %>% filter(term == "log(tot_bmr_prov)")
dn_formal_ols_coef_prov_rc$year <- rep(seq(2001, 2015), each = nrow(dn_formal_ols_coef_prov_rc) / length(seq(2001, 2015)))

# By south 

dn_formal_ols_prov_rc_n <- (list(
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn,
        subset(dn01, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn,
        subset(dn02, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn,
        subset(dn03, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn,
        subset(dn04, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn,
        subset(dn05, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn,
        subset(dn06, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio07 | lhdn,
        subset(dn07, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio08 | lhdn,
        subset(dn08, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio09 | lhdn,
        subset(dn09, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio10 | lhdn,
        subset(dn10, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio11 | lhdn,
        subset(dn11, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio12 | lhdn,
        subset(dn12, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio13 | lhdn,
        subset(dn13, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio14 | lhdn,
        subset(dn14, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio15 | lhdn,
        subset(dn15, south == 0),
        vcov = ~tinh)))

dn_formal_ols_prov_rc_s <- (list(
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn,
        subset(dn01, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn,
        subset(dn02, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn,
        subset(dn03, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn,
        subset(dn04, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn,
        subset(dn05, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn,
        subset(dn06, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio07 | lhdn,
        subset(dn07, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio08 | lhdn,
        subset(dn08, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio09 | lhdn,
        subset(dn09, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio10 | lhdn,
        subset(dn10, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio11 | lhdn,
        subset(dn11, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio12 | lhdn,
        subset(dn12, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio13 | lhdn,
        subset(dn13, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio14 | lhdn,
        subset(dn14, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio15 | lhdn,
        subset(dn15, south == 1),
        vcov = ~tinh)))

dn_formal_ols_prov_rc_coef_n <- lapply(dn_formal_ols_prov_rc_n, tidy)
dn_formal_ols_prov_rc_coef_s <- lapply(dn_formal_ols_prov_rc_s, tidy)
dn_formal_ols_prov_rc_coef_n <- do.call(rbind, dn_formal_ols_prov_rc_coef_n) %>% filter(term == "log(tot_bmr_prov)")
dn_formal_ols_prov_rc_coef_s <- do.call(rbind, dn_formal_ols_prov_rc_coef_s) %>% filter(term == "log(tot_bmr_prov)")
dn_formal_ols_prov_rc_coef_n$year <- rep(seq(2001, 2015), each = nrow(dn_formal_ols_prov_rc_coef_n) / length(seq(2001, 2015)))
dn_formal_ols_prov_rc_coef_s$year <- rep(seq(2001, 2015), each = nrow(dn_formal_ols_prov_rc_coef_s) / length(seq(2001, 2015)))

dn_formal_ols_prov_rc_coef_n$group <- "North"
dn_formal_ols_prov_rc_coef_s$group <- "South"
dn_formal_ols_prov_rc_coef_ns <- rbind(dn_formal_ols_prov_rc_coef_n, dn_formal_ols_prov_rc_coef_s)

##################################
# Firm level FE - FORMAL WORKERS #
##################################

dn_formal_fe_prov_rc <- (list(
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn + nganh_kd,
        dn01,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn + nganh_kd,
        dn02,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn + nganh_kd,
        dn03,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn + nganh_kd,
        dn04,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn + nganh_kd,
        dn05,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn + nganh_kd,
        dn06,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio07 | lhdn + nganh_kd,
        dn07,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio08 | lhdn + nganh_kd,
        dn08,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio09 | lhdn + nganh_kd,
        dn09,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio10 | lhdn + nganh_kd,
        dn10,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio11 | lhdn + nganh_kd,
        dn11,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio12 | lhdn + nganh_kd,
        dn12,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio13 | lhdn + nganh_kd,
        dn13,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio14 | lhdn + nganh_kd,
        dn14,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio15 | lhdn + nganh_kd,
        dn15,
        vcov = ~tinh)))

dn_formal_fe_coef_prov_rc<- lapply(dn_formal_fe_prov_rc, tidy)
dn_formal_fe_coef_prov_rc <- do.call(rbind, dn_formal_fe_coef_prov_rc) %>% filter(term == "log(tot_bmr_prov)")
dn_formal_fe_coef_prov_rc$year <- rep(seq(2001, 2015), each = nrow(dn_formal_fe_coef_prov_rc) / length(seq(2001, 2015)))

# By south 

dn_formal_fe_prov_rc_n <- (list(
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn + nganh_kd,
        subset(dn01, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn + nganh_kd,
        subset(dn02, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn + nganh_kd,
        subset(dn03, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn + nganh_kd,
        subset(dn04, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn + nganh_kd,
        subset(dn05, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn + nganh_kd,
        subset(dn06, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio07 | lhdn + nganh_kd,
        subset(dn07, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio08 | lhdn + nganh_kd,
        subset(dn08, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio09 | lhdn + nganh_kd,
        subset(dn09, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio10 | lhdn + nganh_kd,
        subset(dn10, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio11 | lhdn + nganh_kd,
        subset(dn11, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio12 | lhdn + nganh_kd,
        subset(dn12, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio13 | lhdn + nganh_kd,
        subset(dn13, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio14 | lhdn + nganh_kd,
        subset(dn14, south == 0),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio15 | lhdn + nganh_kd,
        subset(dn15, south == 0),
        vcov = ~tinh)))

dn_formal_fe_prov_rc_s <- (list(
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn + nganh_kd,
        subset(dn01, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn + nganh_kd,
        subset(dn02, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sex_ratio | lhdn + nganh_kd,
        subset(dn03, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn + nganh_kd,
        subset(dn04, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn + nganh_kd,
        subset(dn05, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio05 | lhdn + nganh_kd,
        subset(dn06, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio07 | lhdn + nganh_kd,
        subset(dn07, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio08 | lhdn + nganh_kd,
        subset(dn08, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio09 | lhdn + nganh_kd,
        subset(dn09, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio10 | lhdn + nganh_kd,
        subset(dn10, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio11 | lhdn + nganh_kd,
        subset(dn11, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio12 | lhdn + nganh_kd,
        subset(dn12, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio13 | lhdn + nganh_kd,
        subset(dn13, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio14 | lhdn + nganh_kd,
        subset(dn14, south == 1),
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov) + sexratio15 | lhdn + nganh_kd,
        subset(dn15, south == 1),
        vcov = ~tinh)))

dn_formal_fe_prov_coef_rc_n <- lapply(dn_formal_fe_prov_rc_n, tidy)
dn_formal_fe_prov_coef_rc_s <- lapply(dn_formal_fe_prov_rc_s, tidy)
dn_formal_fe_prov_coef_rc_n <- do.call(rbind, dn_formal_fe_prov_coef_rc_n) %>% filter(term == "log(tot_bmr_prov)")
dn_formal_fe_prov_coef_rc_s <- do.call(rbind, dn_formal_fe_prov_coef_rc_s) %>% filter(term == "log(tot_bmr_prov)")
dn_formal_fe_prov_coef_rc_n$year <- rep(seq(2001, 2015), each = nrow(dn_formal_fe_prov_coef_rc_n) / length(seq(2001, 2015)))
dn_formal_fe_prov_coef_rc_s$year <- rep(seq(2001, 2015), each = nrow(dn_formal_fe_prov_coef_rc_s) / length(seq(2001, 2015)))

dn_formal_fe_prov_coef_rc_n$group <- "North"
dn_formal_fe_prov_coef_rc_s$group <- "South"
dn_formal_fe_prov_coef_rc_ns <- rbind(dn_formal_fe_prov_coef_rc_n, dn_formal_fe_prov_coef_rc_s)

####################
# Casualties - OLS #
####################

#################
# Province level#
#################

# OLS

dn_prov_ols_models <- list(
  feols(workerratio ~ log(tot_bmr_prov),
        dn01_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn02_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn03_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn04_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn05_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn06_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn07_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn08_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn09_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn10_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn11_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn12_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn13_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn14_prov,
        vcov = ~tinh),
  feols(workerratio ~ log(tot_bmr_prov),
        dn15_prov,
        vcov = ~tinh)
)

dn_prov_ols_coef <- lapply(dn_prov_ols_models, tidy)
dn_prov_ols_coef <- do.call(rbind, dn_prov_ols_coef) %>% filter(term != "(Intercept)")
dn_prov_ols_coef$year <- rep(seq(2001, 2015), each = nrow(dn_prov_ols_coef) / length(seq(2001, 2015)))

# By South 

dn_prov_ols_s <- list(
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn01_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn02_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn03_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn04_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn05_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn06_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn07_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn08_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn09_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn10_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn11_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn12_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn13_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn14_prov, south == 1),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn15_prov, south == 1),
        vcov = ~tinh)
)

dn_prov_ols_n <- list(
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn01_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn02_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn03_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn04_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn05_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn06_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn07_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn08_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn09_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn10_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn11_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn12_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn13_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn14_prov, south == 0),
        vcov = ~tinh),
  feols(tot_workerratio ~ log(tot_bmr_prov),
        subset(dn15_prov, south == 0),
        vcov = ~tinh)
)

dn_prov_ols_coef_s <- lapply(dn_prov_ols_s, tidy)
dn_prov_ols_coef_s <- do.call(rbind, dn_prov_ols_coef_s) %>% filter(term != "(Intercept)")
dn_prov_ols_coef_s$year <- rep(seq(2001, 2015), each = nrow(dn_prov_ols_coef_s) / length(seq(2001, 2015)))

dn_prov_ols_coef_n <- lapply(dn_prov_ols_n, tidy)
dn_prov_ols_coef_n <- do.call(rbind, dn_prov_ols_coef_n) %>% filter(term != "(Intercept)")
dn_prov_ols_coef_n$year <- rep(seq(2001, 2015), each = nrow(dn_prov_ols_coef_n) / length(seq(2001, 2015)))

dn_prov_ols_coef_n$group <- "North"
dn_prov_ols_coef_s$group <- "South"
dn_prov_ols_coef_ns <- rbind(dn_prov_ols_coef_n, dn_prov_ols_coef_s)
